platform :ios do
    desc "Run iOS tests"
    lane :tests do
        run_tests(scheme: "LatticeDev", xcargs: "-skipMacroValidation")
    end

    desc "Push a new beta build to TestFlight"
    lane :deploy do
        setup_ci

        app_store_connect_api_key(
            key_id: ENV["APP_STORE_CONNECT_API_KEY_ID"],
            issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
            key_content: ENV["APP_STORE_CONNECT_API_KEY_CONTENT"]
        )

        sync_code_signing(
            readonly: true,
            platform: "ios",
            type: "appstore",
            additional_cert_types: [],
            app_identifier: ["build.miguel.Lattice"],
        )

        increment_build_number(
            xcodeproj: "Lattice.xcodeproj",
            build_number: latest_testflight_build_number(platform: "ios")  + 1
        )

        build_app(scheme: "Lattice", xcargs: "-skipMacroValidation")
        # sentry_debug_files_upload(auth_token: ENV["SENTRY_TOKEN"], org_slug: 'm1guelpf', project_slug: 'lattice', derived_data: true, include_sources: true)
        sentry_upload_build(auth_token: ENV["SENTRY_TOKEN"], org_slug: 'm1guelpf', project_slug: 'lattice', build_configuration: 'Release')
        upload_to_testflight(distribute_external: false, changelog: "")
    end
end

platform :mac do
    desc "Run macOS tests"
    lane :tests do
        run_tests(scheme: "LatticeDev", xcargs: "-skipMacroValidation")
    end

    desc "Push a new beta build to TestFlight"
    lane :deploy do
        setup_ci

        app_store_connect_api_key(
            key_id: ENV["APP_STORE_CONNECT_API_KEY_ID"],
            issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
            key_content: ENV["APP_STORE_CONNECT_API_KEY_CONTENT"]
        )

        sync_code_signing(
            readonly: true,
            type: "appstore",
            platform: "macos",
            app_identifier: ["build.miguel.Lattice"],
            additional_cert_types: ["mac_installer_distribution"],
        )

        increment_build_number(
            xcodeproj: "Lattice.xcodeproj",
            build_number: latest_testflight_build_number(platform: "osx") + 1
        )

        build_app(
            sdk: "macosx",
            scheme: "Lattice",
            xcargs: "-skipMacroValidation"
        )
        sentry_debug_files_upload(auth_token: ENV["SENTRY_TOKEN"], org_slug: 'm1guelpf', project_slug: 'lattice', derived_data: true, include_sources: true)
        upload_to_testflight(distribute_external: false, changelog: "")
    end
end

desc "Generate profiles and certificates"
lane :generate_profiles_and_certificates do
	sync_code_signing(type: "development", app_identifier: ["build.miguel.Lattice"], readonly: false, platform: "ios")
	sync_code_signing(type: "development", app_identifier: ["build.miguel.Lattice"], readonly: false, platform: "macos")

    sync_code_signing(type: "appstore", app_identifier: ["build.miguel.Lattice"], readonly: false, platform: "ios")
    sync_code_signing(type: "appstore", app_identifier: ["build.miguel.Lattice"], readonly: false, platform: "macos", additional_cert_types: ["mac_installer_distribution"])
end
